larger font

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# rewrite with lua or zig?
+
 set -e
 
 usage()
@@ -23,24 +25,18 @@ usage()
         run some -- args # where some is executable\n'
 }
 
-#
-# generate temporary file name (starting with "/") for compiler
-#
-gen_tempfile()
+warn()
 {
-    local tempfile
-    tempfile=$(mktemp)
-    if [ "${tempfile#/}" = "$tempfile" ]; then
-        # should not happen
-        printf 'tempfile name not starts with slash: %s\n' "$tempfile" >&2
-        [ -e "$tempfile" ] && command rm -- "$tempfile"
-        exit 1
-    fi
-    # tempfile name is ending with ".build"; it's ok to pass it via $()
-    printf "$tempfile"
+    printf "$@" >&2
 }
 
-if (( $# == 0 )) || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
+abort()
+{
+    warn "$@"
+    exit 1
+}
+
+if [ $# -eq 0 ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
     usage
     exit 0
 fi
@@ -66,8 +62,7 @@ if [ "${source_file#-}" != "${source_file}" ] || \
 fi
 
 if ! [ -f "$source_file" ]; then
-    printf "file not found: %s\n" "$source_file" >&2
-    exit 1
+    abort "file not found: %s\n" "$source_file"
 fi
 
 #
@@ -87,19 +82,14 @@ done
 # guess additional args based on file extension
 #
 case ${source_file##*.} in
-    c)
-        tempfile=$(gen_tempfile)
-        compiler=cc
-        compiler_args=("$source_file" "${compiler_args[@]}" -o "$tempfile")
-        ;;
-    cpp)
-        tempfile=$(gen_tempfile)
-        compiler=c++
-        compiler_args=("$source_file" "${compiler_args[@]}" -o "$tempfile")
-        ;;
-    rs)
-        tempfile=$(gen_tempfile)
-        compiler=rustc
+    c|cpp|rs)
+        case ${source_file##*.} in
+            c) compiler=cc ;;
+            cpp) compiler=c++ ;;
+            rs) compiler=rust ;;
+        esac
+        # TODO quote?
+        tempfile=$(mktemp)
         compiler_args=("$source_file" "${compiler_args[@]}" -o "$tempfile")
         ;;
     go)
@@ -115,8 +105,7 @@ case ${source_file##*.} in
             interpreter=${interpreter#\#\!}
             no_compiler=true
         else
-            printf 'compiler not found for %s\n' "$source_file" >&2
-            exit 1
+            abort 'compiler not found for %s\n' "$source_file"
         fi
         ;;
 esac
